### ISSUE TITLE
Swoop crashes on startup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ronwalf/swoop#13]
```
What steps will reproduce the problem?

Start Swoop.

What is the expected output? What do you see instead?

Unable to load old SWOOP Preferences from disk..
Try creating renderer org.mindswap.swoop.renderer.ontology.SwoopOntologyInfo
Try creating renderer
org.mindswap.swoop.renderer.ontology.SwoopSpeciesValidationRenderer
Try creating reasoner org.mindswap.swoop.reasoner.PelletReasoner
Try creating reasoner org.mindswap.swoop.reasoner.SwoopRDFSReasoner
Try creating reasoner org.mindswap.swoop.reasoner.SwoopToldReasoner
Unable to load old Version Repository from disk
jar:file:/export/u1/homes/elenius/download/swoop-2.3beta4/lib/swoop.jar!/org/min
dswap/swoop/utils/Exception
in thread "main" java.lang.NullPointerException
        at
javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:495)
        at java.awt.Container.preferredSize(Container.java:1670)
        at java.awt.Container.getPreferredSize(Container.java:1655)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1646)
        at
javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTab
bedPaneUI.java:2297)
        at
javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.preferredLayoutSize(Ba
sicTabbedPaneUI.java:2271)
        at java.awt.Container.preferredSize(Container.java:1670)
        at java.awt.Container.getPreferredSize(Container.java:1655)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1646)
        at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:720)
        at java.awt.Container.preferredSize(Container.java:1670)
        at java.awt.Container.getPreferredSize(Container.java:1655)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1646)
        at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:720)
        at java.awt.Container.preferredSize(Container.java:1670)
        at java.awt.Container.getPreferredSize(Container.java:1655)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1646)
        at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:720)
        at java.awt.Container.preferredSize(Container.java:1670)
        at java.awt.Container.getPreferredSize(Container.java:1655)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1646)
        at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:720)
        at java.awt.Container.preferredSize(Container.java:1670)
        at java.awt.Container.getPreferredSize(Container.java:1655)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1646)
        at
javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.getPreferre
dSizeOfComponent(BasicSplitPaneUI.java:1632)
        at
javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.getPreferre
dSizes(BasicSplitPaneUI.java:1865)
        at
javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.resetToPref
erredSizes(BasicSplitPaneUI.java:1902)
        at
javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.layoutConta
iner(BasicSplitPaneUI.java:1331)
        at java.awt.Container.layout(Container.java:1486)
        at java.awt.Container.doLayout(Container.java:1475)
        at java.awt.Container.validateTree(Container.java:1573)
        at java.awt.Container.validateTree(Container.java:1580)
        at java.awt.Container.validateTree(Container.java:1580)
        at java.awt.Container.validateTree(Container.java:1580)
        at java.awt.Container.validateTree(Container.java:1580)
        at java.awt.Container.validateTree(Container.java:1580)
        at java.awt.Container.validateTree(Container.java:1580)
        at java.awt.Container.validate(Container.java:1545)
        at java.awt.Window.show(Window.java:890)
        at java.awt.Component.show(Component.java:1456)
        at java.awt.Component.setVisible(Component.java:1408)
        at java.awt.Window.setVisible(Window.java:871)
        at org.mindswap.swoop.Swoop.main(Swoop.java:73)


What version of the product are you using? On what operating system?

2.3 beta 4 on

Linux 2.6.23.14-107.fc8 #1 SMP Mon Jan 14 22:07:11 EST 2008 x86_64 x86_64
x86_64 GNU/Linux

Please provide any additional information below.


```

Original issue reported on code.google.com by `elen...@gmail.com` on 2 Feb 2008 at 1:38

**Comment by GoogleCodeExporter** [comment]
```
Works on Ubuntu 7.10 (kernel 2.6.22)
```

Original comment by `elen...@gmail.com` on 2 Feb 2008 at 1:44
